app/routes/admin.py
# app/routes/admin.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort
from flask_login import login_required, current_user
from ..models import Leaderboard
from .. import db
import os

admin = Blueprint("admin", __name__, url_prefix="/admin")

def admin_required(f):
    from functools import wraps
    @wraps(f)
    def wrapper(*args, **kwargs):
        if not current_user.is_authenticated or not current_user.is_admin:
            abort(403)
        return f(*args, **kwargs)
    return wrapper

@admin.route("/pending")
@login_required
@admin_required
def pending():
    pending_entries = Leaderboard.query.filter_by(verified=False).all()
    return render_template("admin_pending.html", entries=pending_entries)

@admin.route("/verify/<int:entry_id>", methods=["POST"])
@login_required
@admin_required
def verify(entry_id):
    entry = Leaderboard.query.get_or_404(entry_id)
    entry.verified = True
    db.session.commit()
    flash("Entry verified", "success")
    return redirect(url_for("admin.pending"))

@admin.route("/reject/<int:entry_id>", methods=["POST"])
@login_required
@admin_required
def reject(entry_id):
    entry = Leaderboard.query.get_or_404(entry_id)
    db.session.delete(entry)
    db.session.commit()
    flash("Entry rejected and deleted", "invalid_time")
    return redirect(url_for("admin.pending"))

app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from ..models import User
from .. import db

auth = Blueprint("auth", __name__)

@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if User.query.filter_by(username=username).first():
            flash("Username taken, please choose another.", "invalid_credentials")
            return redirect(url_for("auth.register"))

        user = User(username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("auth.login"))

    return render_template("register.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for("main.index"))
        else:
            flash("Wrong username or password", "invalid_credentials")
            return redirect(url_for("auth.login"))

    return render_template("login.html")


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

app/routes/main.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    current_app,
    abort
)
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
import os
import uuid
import boto3

s3 = boto3.client("s3")

from .. import db
from ..models import Leaderboard

CUPS = {
    # base game
    "Mushroom Cup": [
        "Mario Kart Stadium",
        "Water Park",
        "Sweet Sweet Canyon",
        "Thwomp Ruins",
    ],
    "Flower Cup": [
        "Mario Circuit (MK8)",
        "Toad Harbor",
        "Twisted Mansion",
        "Shy Guy Falls",
    ],
    "Star Cup": [
        "Sunshine Airport",
        "Dolphin Shoals",
        "Electrodrome",
        "Mount Wario",
    ],
    "Special Cup": [
        "Cloudtop Cruise",
        "Bone-Dry Dunes",
        "Bowser's Castle (MK8)",
        "Rainbow Road (MK8)",
    ],
    "Shell Cup": [
        "Moo Moo Meadows (Wii)",
        "Mario Circuit (GBA)",
        "Cheep Cheep Beach (DS)",
        "Toad's Turnpike (N64)",
    ],
    "Banana Cup": [
        "Dry Dry Desert (GCN)",
        "Donut Plains 3 (SNES)",
        "Royal Raceway (N64)",
        "DK Jungle (3DS)",
    ],
    "Leaf Cup": [
        "Wario Stadium (DS)",
        "Sherbet Land (GCN)",
        "Music Park (3DS)",
        "Yoshi Valley (N64)",
    ],
    "Lightning Cup": [
        "Tick-Tock Clock (DS)",
        "Piranha Plant Slide (3DS)",
        "Grumble Volcano (Wii)",
        "Rainbow Road (N64)",
    ],
    "Egg Cup": [
        "Yoshi Circuit (GCN)",
        "Excitebike Arena",
        "Dragon Driftway",
        "Mute City (F-Zero)",
    ],
    "Triforce Cup": [
        "Wario's Gold Mine (Wii)",
        "Rainbow Road (SNES)",
        "Ice Ice Outpost",
        "Hyrule Circuit",
    ],
    "Crossing Cup": [
        "Baby Park (GCN)",
        "Cheese Land (GBA)",
        "Wild Woods",
        "Animal Crossing",
    ],
    "Bell Cup": [
        "Neo Bowser City (3DS)",
        "Ribbon Road (GBA)",
        "Super Bell Subway",
        "Big Blue (F-Zero)",
    ],
    # DLC
    "Golden Dash Cup": [
        "Paris Promenade (Tour)",
        "Toad Circuit (3DS)",
        "Choco Mountain (N64)",
        "Coconut Mall (Wii)",
    ],
    "Lucky Cat Cup": [
        "Tokyo Blur (Tour)",
        "Shroom Ridge (DS)",
        "Sky Garden (GBA)",
        "Ninja Hideaway (Tour)",
    ],
    "Turnip Cup": [
        "New York Minute (Tour)",
        "Mario Circuit 3 (SNES)",
        "Kalimari Desert (N64)",
        "Waluigi Pinball (DS)",
    ],
    "Propeller Cup": [
        "Sydney Sprint (Tour)",
        "Snow Land (GBA)",
        "Mushroom Gorge (Wii)",
        "Sky-High Sundae",
    ],
    "Rock Cup": [
        "London Loop (Tour)",
        "Boo Lake (GBA)",
        "Rock Rock Mountain (3DS)",
        "Maple Treeway (Wii)",
    ],
    "Moon Cup": [
        "Berlin Byways (Tour)",
        "Peach Gardens (DS)",
        "Merry Mountain (Tour)",
        "Rainbow Road (3DS)",
    ],
    "Fruit Cup": [
        "Amsterdam Drift (Tour)",
        "Riverside Park (GBA)",
        "DK Summit (Wii)",
        "Yoshi's Island",
    ],
    "Boomerang Cup": [
        "Bangkok Rush (Tour)",
        "Mario Circuit (DS)",
        "Waluigi Stadium (GCN)",
        "Singapore Speedway (Tour)",
    ],
    "Feather Cup": [
        "Athens Dash (Tour)",
        "Daisy Cruiser (GCN)",
        "Moonview Highway (Wii)",
        "Squeaky Clean Sprint",
    ],
    "Cherry Cup": [
        "Los Angeles Laps (Tour)",
        "Sunset Wilds (GBA)",
        "Koopa Cape (Wii)",
        "Vancouver Velocity (Tour)",
    ],
    "Acorn Cup": [
        "Rome Avanti (Tour)",
        "DK Mountain (GCN)",
        "Daisy Circuit (Wii)",
        "Piranha Plant Cove",
    ],
    "Spiny Cup": [
        "Madrid Drive (Tour)",
        "Rosalina's Ice World (3DS)",
        "Bowser Castle 3 (SNES)",
        "Rainbow Road (Wii)",
    ],
}

TRACKS = [track for tracks in CUPS.values() for track in tracks]

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render_template("index.html", maps=TRACKS, CUPS=CUPS)

@main.route("/leaderboard/<map_name>")
def leaderboard(map_name):
    if map_name not in TRACKS:
        abort(404)

    times = Leaderboard.query.filter_by(track=map_name, verified=True).all()
    # sort times, only render top 10 on leaderboard
    full_times = sorted(
        times, key=lambda x: x.time_mins + (x.time_s / 60) + (x.time_ms / 60000)
    )

    times = full_times[:10]

    user_index = None

    if(
        current_user.is_authenticated 
        and current_user.scores.filter_by(track=map_name, verified=True).first() is not None
    ):
        if current_user.scores.filter_by(track=map_name, verified=True).first() not in times:
            times.append(current_user.scores.filter_by(track=map_name, verified=True).first())
            user_index = full_times.index(current_user.scores.filter_by(track=map_name, verified=True).first())

    return render_template(
        "leaderboard.html",
        map_name=map_name,
        times=times,
        user_index=user_index
    )

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg"}

def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS

@main.route("/submit", methods=["POST"])
@login_required
def submit():
    map_name = request.form.get("map_name", "")
    try:
        time_mins = int(request.form.get("time_mins", ""))
        time_s = int(request.form.get("time_s", ""))
        time_ms = int(request.form.get("time_ms", ""))
    except ValueError:
        return redirect(url_for("main.leaderboard", map_name=map_name))

    if not validate_time(map_name, time_mins, time_s, time_ms, TRACKS):
        flash("Invalid Time", "invalid_time")
        return redirect(url_for("main.leaderboard", map_name=map_name))

    screenshot = request.files.get("screenshot")

    if not screenshot:
        flash("Missing screenshot file.", "missing_screenshot")
        return redirect(url_for("main.leaderboard", map_name=map_name))

    filename = secure_filename(screenshot.filename)

    if not allowed_file(filename):
        flash("Invalid screenshot file type. Please upload a PNG or JPG file"
        , "invalid_screenshot")
        return redirect(url_for("main.leaderboard", map_name=map_name))
    
    unique_name = f"{uuid.uuid4().hex}_{filename}"

    if current_app.config["USE_S3"]:
        # upload to s3 !!
        s3.upload_fileobj(
            screenshot,
            current_app.config["S3_BUCKET_NAME"],
            unique_name,  # folder inside the bucket
            ExtraArgs={"ContentType": screenshot.content_type},
        )
        file_url = f"https://{current_app.config['S3_BUCKET_NAME']}.s3.us-west-2.amazonaws.com/{unique_name}"
    else:
        # save locally
        file_path = os.path.join(current_app.config["UPLOAD_FOLDER"], unique_name)
        screenshot.save(file_path)
        file_url = f"/static/uploads/{unique_name}"

    existing_entry = Leaderboard.query.filter_by(
        track=map_name, user_id=current_user.id
    ).first()

    if existing_entry:
        # update existing entry
        existing_entry.time_mins = time_mins
        existing_entry.time_s = time_s
        existing_entry.time_ms = time_ms
        existing_entry.screenshot_path = file_url
        existing_entry.verified = False
        flash("Entry updated! Awaiting verification...", "pending")
    else:
        # new entry if not found
        new_entry = Leaderboard(
            track=map_name,
            time_mins=time_mins,
            time_s=time_s,
            time_ms=time_ms,
            user_id=current_user.id,
            screenshot_path=file_url,
            verified=False,
        )
        flash("New entry created! Awaiting verification...", "pending")
        db.session.add(new_entry)

    db.session.commit()

    return redirect(url_for("main.leaderboard", map_name=map_name))

def validate_time(map_name: str, time_mins: int, time_s: int,
    time_ms: int, tracks: list[str]) -> bool:
    if map_name not in tracks:
        return False
    if time_mins < 0 or time_mins >= 60:
        return False
    if time_s < 0 or time_s >= 60:
        return False
    if time_ms < 0 or time_ms >= 1000:
        return False
    return True

app/templates/admin_pending.html
{% extends "base.html" %}
{% block content %}
  <h2>Pending Submissions</h2>

  {% with flashes = get_flashed_messages(with_categories=true) %}
    {% if flashes %}
    <ul class="flashes">
      {% for category, message in flashes %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  {% endwith %}

  {% if entries %}
    <table border="1" cellpadding="6">
      <tr>
        <th>ID</th>
        <th>User</th>
        <th>Track</th>
        <th>Time</th>
        <th>Screenshot</th>
        <th>Actions</th>
      </tr>
      {% for e in entries %}
      <tr>
        <td>{{ e.id }}</td>
        <td>{{ e.user.username if e.user else "?" }}</td>
        <td>{{ e.track }}</td>
        <td>{{ e.time_mins }}:{{ "%02d"|format(e.time_s) }}.{{ "%03d"|format(e.time_ms) }}</td>
        <td>
          {% if e.screenshot_path.startswith('http') %}
            <a href="{{ e.screenshot_path }}" target="_blank" style="color: white; text-decoration: none;">
              View</a>
          {% else %}
            <a href="{{ url_for('static', filename=e.screenshot_path.split('static/')[-1]) }}" 
            target="_blank" style="color: white; text-decoration: none;">
              View</a>
          {% endif %}
        </td>
        <td>
          <form action="{{ url_for('admin.verify', entry_id=e.id) }}" method="POST" style="display:inline;">
            <button type="submit" style="color: green; text-decoration: none;">Approve</button>
          </form> |
          <form action="{{ url_for('admin.reject', entry_id=e.id) }}" method="POST" style="display:inline;">
            <button type="submit" style="color: red; text-decoration: none;">Reject</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No pending submissions!</p>
  {% endif %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mario Kart 8 Deluxe Leaderboard</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap" rel="stylesheet">
</head>
<body class="layout">
  <header class="site-header">
    <div class="bg-wrapper">
    <img src="/static/img/maps/mushroom-gorge.svg" alt="">
    </div>
    <h1><a href="{{ url_for('main.index') }}">Mario Kart 8 Deluxe Leaderboard</a></h1>
  </header>

  <main class="page-content">
    {% block content %}{% endblock %}
  </main>

  <footer class="site-footer">
    {% if current_user.is_authenticated %}
      <div class="not-signed-up">
        <a href="{{ url_for('auth.logout') }}">Logout</a>
      </div>
    {% else %}
    <small><a href="https://github.com/lucastidy/" style="color: #a6e3eb; text-decoration: none;">my github <-</a></small>
    {% endif %}
  </footer>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
  {% if not current_user.is_authenticated %}
  <div class="sign-up-buttons">
    <a href="{{ url_for('auth.register') }}">Register to submit a time!</a></p>
    <a href="{{ url_for('auth.login') }}">Login</a></p>
  </div>
  {% endif %}
  <h2 class="map_title">Choose a Track:</h2>
  {% for cup, tracks in CUPS.items() %}
    <div class="cup-container">
      <h3 class="cup-title">{{ cup }}</h3>
      <img src="/static/img/cups/{{ cup|replace(' ', '-')|lower }}.png" alt="" style="  transform: scale(0.7);"> 
    </div>
    <ul class="track-list">
      {% for m in tracks %}
        <li>
          <a href="{{ url_for('main.leaderboard', map_name=m) }}" class="submit-button">{{ m }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endblock %}

app/templates/leaderboard.html
{% extends "base.html" %}
{% block content %}
  <h2 class="map_title">{{ map_name }}</h2>

  <div class="board-wrapper">
    <table class="board">
      <thead>
        <tr><th>#</th><th>Player</th><th>Time</th></tr>
      </thead>
      <tbody>
        {% for entry in times %}
          <tr>
            {% if loop.last and user_index is not none %}
              <td style="color: rgb(255, 145, 0); font-weight: bold;">{{ user_index + 1 }}</td>
            {% else %}
              <td>{{ loop.index }}</td>
            {% endif %}
              <td>{{ entry.user.username }}</td>
              <td>{{ "%02d:%02d:%03d"|format(entry.time_mins, entry.time_s, entry.time_ms) }}</td>
          </tr>
        {% else %}
          <tr><td colspan="3" class="empty">No times yet — be the first!</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}
</div>

  <h3>Submit a Time:</h3>
  {% if current_user.is_authenticated %}
    <form method="POST" 
          action="{{ url_for('main.submit') }}" 
          enctype="multipart/form-data"
          class="submit-form">
      <input type="hidden" name="map_name" value="{{ map_name }}">
      <div class="input-wrapper">
        <input type="number" name="time_mins" step="0.01" min="0" placeholder="m" required>
      </div>
      <div class="input-wrapper">
        <input type="number" name="time_s" step="0.01" min="0" placeholder="s" required>
      </div>
      <div class="input-wrapper">
        <input type="number" name="time_ms" step="0.01" min="0" placeholder="ms" required>
      </div>
      <label>Proof of time: <input type="file" name="screenshot" accept="image/*" required></label>
      <button type="submit" class="submit-button">Submit!</button>
    </form>
  {% else %}
      <div>
        <p>You must be logged in to submit a time</p>
      </div>
      <div class="not-signed-up">
        <a href="{{ url_for('auth.login') }}">Login</a>
      </div>
  {% endif %}

  <p class="back-link"><a href="{{ url_for('main.index') }}">← Back to tracks</a></p>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}

<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}
</div>

<form method="POST" class="submit-form-signup">
  <div class="input-wrapper">
    <input name="username" placeholder="Username" required>
  </div>
  <div class="input-wrapper">
    <input name="password" type="password" placeholder="Password" required>
  </div>
  <button type="submit" class="submit-button-signup">Login!</button>
</form>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block content %}

<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}
</div>

<form method="POST" class="submit-form-signup">
  <div class="input-wrapper">
    <input name="username" placeholder="Username" required>
  </div>
  <div class="input-wrapper">
    <input name="password" type="password" placeholder="Password" required>
  </div>
  <button type="submit" class="submit-button-signup">Register!</button>
</form>
{% endblock %}